Cloud bastion
Otus-DevOps-2023-09/zippaa_infra pull request #3
Opened 2023-10-22 11:12 UTC by zippaa

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-10-23 17:47 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Оставил комментарий к файлу, нужно поправить
Приключение на 10 минут =)

2023-10-23 17:47 UTC, mrgreyves commented on README.md
> +bastion_IP: 51.250.80.225\
Лишний символ \ в строке
Наверное просто механическая ошибка =)

2023-10-24 09:39 UTC, zippaa commented on README.md
> +bastion_IP: 51.250.80.225\
убрал символы /

2023-10-24 16:11 UTC, mrgreyves approved these changes
Здравствуйте!)
Вот теперь все круто =)

2023-10-25 09:43 UTC, merged